// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDStBJJjXOS7yBHxS2dYTl4hJeBeHVbtQc',
    appId: '1:135380798852:web:66c93c11d1634a14a6e1d1',
    messagingSenderId: '135380798852',
    projectId: 'volunteer-app-ecc3f',
    authDomain: 'volunteer-app-ecc3f.firebaseapp.com',
    storageBucket: 'volunteer-app-ecc3f.appspot.com',
    measurementId: 'G-ZPRVKW79WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXDG4LrgS701kCaSx9FPWnLFEY6cmM7Ls',
    appId: '1:135380798852:android:b280b6a68a7d4b30a6e1d1',
    messagingSenderId: '135380798852',
    projectId: 'volunteer-app-ecc3f',
    storageBucket: 'volunteer-app-ecc3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpRp1aUwLs9c_oC7wYu9YEZp-IMXRrx4',
    appId: '1:135380798852:ios:eb29c6c75155dc85a6e1d1',
    messagingSenderId: '135380798852',
    projectId: 'volunteer-app-ecc3f',
    storageBucket: 'volunteer-app-ecc3f.appspot.com',
    iosBundleId: 'com.example.volunteerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpRp1aUwLs9c_oC7wYu9YEZp-IMXRrx4',
    appId: '1:135380798852:ios:41c364bb59199baba6e1d1',
    messagingSenderId: '135380798852',
    projectId: 'volunteer-app-ecc3f',
    storageBucket: 'volunteer-app-ecc3f.appspot.com',
    iosBundleId: 'com.example.volunteerApplication.RunnerTests',
  );
}
